apiVersion: apps/v1
kind: Deployment
metadata:
  name: oceanshield-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oceanshield-api
  template:
    metadata:
      labels:
        app: oceanshield-api
    spec:
      containers:
        - name: oceanshield-api
          image: oceanshield-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
